var proj4 = require('proj4');

function format(inputDate) {
    var date = new Date(inputDate);
    if (!isNaN(date.getTime())) {
        // Months use 0 index.
        return date.getDate() + '/' + ("0" + String((parseInt(date.getMonth()) + 1))).slice(-2) + '/' + date.getFullYear();
    }
}

exports.formatting = function(jsonContent){
	 jsonContent.forEach(element => {
		
		if (element.today) {
			element.today_date = format(element.today)
		}
		
		element["form_logo"] = "metadata/form_logo.png";
		element["carto_img"] = "carto/pr_coord_" + element["_index"] + ".png";
		element["carto_refoulement_img"] = "carto/pr_coord_refoulement_" + element["_index"] + ".png";
		
		if ('INFO_GENERAL-INFO_GENERAL-OPE_NOM_OTHER' in element &&  element['INFO_GENERAL-INFO_GENERAL-OPE_NOM_OTHER'] != ""){
			element["OPE_NOM_FINAL"] = element['INFO_GENERAL-INFO_GENERAL-OPE_NOM_OTHER'];
		}else{
			element["OPE_NOM_FINAL"] = element['INFO_GENERAL-INFO_GENERAL-OPE_NOM'];
		}
		
		if ('INFO_GENERAL-INFO_GENERAL-PR_SYSTEME_OTHER' in element &&  element['INFO_GENERAL-INFO_GENERAL-PR_SYSTEME_OTHER'] != ""){
			element["PR_SYSTEME_FINAL"] = element['INFO_GENERAL-INFO_GENERAL-PR_SYSTEME_OTHER'];
		}else{
			element["PR_SYSTEME_FINAL"] = element['INFO_GENERAL-INFO_GENERAL-PR_SYSTEME'];
		}
		
		if ('INFO_GENERAL-INFO_GENERAL-PR_NOM_OTHER' in element &&  element['INFO_GENERAL-INFO_GENERAL-PR_NOM_OTHER'] != ""){
			element["PR_NOM_FINAL"] = element['INFO_GENERAL-INFO_GENERAL-PR_NOM_OTHER'];
		}else{
			element["PR_NOM_FINAL"] = element['INFO_GENERAL-INFO_GENERAL-PR_NOM'];
		}
		
		//TODO ERREUR ! Confusion entre Présence Débimetre et TARAGE !
		element["PRESENCE_DEBIMETRE_FINAL"] = "";
		if ('ENV_SECURITE-ENV_SECURITE_TARAGE-ENV_SECURITE_TARAGE-PRESENCE_OUI_NON' in element &&  element['ENV_SECURITE-ENV_SECURITE_TARAGE-ENV_SECURITE_TARAGE-PRESENCE_OUI_NON'] != ""){
			element["PRESENCE_DEBIMETRE_FINAL"] = element['ENV_SECURITE-ENV_SECURITE_TARAGE-ENV_SECURITE_TARAGE-PRESENCE_OUI_NON'];
		}
		element["DEBIMETRE_NOTE_FINAL"] = "";
		if ('ENV_SECURITE-ENV_SECURITE_TARAGE-ENV_SECURITE_TARAGE-NOTE' in element &&  element['ENV_SECURITE-ENV_SECURITE_TARAGE-ENV_SECURITE_TARAGE-NOTE'] != ""){
			element["DEBIMETRE_NOTE_FINAL"] = element['ENV_SECURITE-ENV_SECURITE_TARAGE-ENV_SECURITE_TARAGE-NOTE'];
		}
		element["DEBIMETRE_PHOTO_FINAL"] = "";
		if ('ENV_SECURITE-ENV_SECURITE_TARAGE-ENV_SECURITE_TARAGE-IMAGE_DEBITMETRE' in element &&  element['ENV_SECURITE-ENV_SECURITE_TARAGE-ENV_SECURITE_TARAGE-IMAGE_DEBITMETRE'] != ""){
			element["DEBIMETRE_PHOTO_FINAL"] = element['ENV_SECURITE-ENV_SECURITE_TARAGE-ENV_SECURITE_TARAGE-IMAGE_DEBITMETRE'];
		}
		
		
		
		try {
			var fromProjection = proj4('EPSG:4326');
			var toProjection = "+proj=lcc +lat_1=49 +lat_2=44 +lat_0=46.5 +lon_0=3 +x_0=700000 +y_0=6600000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs";
			var new_coord = proj4(fromProjection,toProjection,[parseFloat(element["INFO_GENERAL-_INFO_GENERAL-PR_COORDS_longitude"]),parseFloat(element["INFO_GENERAL-_INFO_GENERAL-PR_COORDS_latitude"])]);
			element["X_2154_FINAL"] = new_coord[0]
			element["Y_2154_FINAL"] = new_coord[1]
		} catch (error) {
			console.error("Eror on reproj point");
		}
		
		
		/***Ajout des m */
		if (element['CARACTERISTIQUES-CARACTERISTIQUES_MARNAGE-CARACTERISTIQUES_MARNAGE_CONSIGNE-CARACTERISTIQUES_MARNAGE_CONSIGNE-ARRET']) {
			element['CARACTERISTIQUES-CARACTERISTIQUES_MARNAGE-CARACTERISTIQUES_MARNAGE_CONSIGNE-CARACTERISTIQUES_MARNAGE_CONSIGNE-ARRET'] = element['CARACTERISTIQUES-CARACTERISTIQUES_MARNAGE-CARACTERISTIQUES_MARNAGE_CONSIGNE-CARACTERISTIQUES_MARNAGE_CONSIGNE-ARRET']+"m"
		}
		if (element['CARACTERISTIQUES-CARACTERISTIQUES_MARNAGE-CARACTERISTIQUES_MARNAGE_CONSIGNE-CARACTERISTIQUES_MARNAGE_CONSIGNE-NIV1']) {
			element['CARACTERISTIQUES-CARACTERISTIQUES_MARNAGE-CARACTERISTIQUES_MARNAGE_CONSIGNE-CARACTERISTIQUES_MARNAGE_CONSIGNE-NIV1'] = element['CARACTERISTIQUES-CARACTERISTIQUES_MARNAGE-CARACTERISTIQUES_MARNAGE_CONSIGNE-CARACTERISTIQUES_MARNAGE_CONSIGNE-NIV1'] + "m"
		}
		if (element['CARACTERISTIQUES-CARACTERISTIQUES_MARNAGE-CARACTERISTIQUES_MARNAGE_CONSIGNE-CARACTERISTIQUES_MARNAGE_CONSIGNE-NIV2']) {
			element['CARACTERISTIQUES-CARACTERISTIQUES_MARNAGE-CARACTERISTIQUES_MARNAGE_CONSIGNE-CARACTERISTIQUES_MARNAGE_CONSIGNE-NIV2'] = element['CARACTERISTIQUES-CARACTERISTIQUES_MARNAGE-CARACTERISTIQUES_MARNAGE_CONSIGNE-CARACTERISTIQUES_MARNAGE_CONSIGNE-NIV2'] + "m"
		}
		if (element['CARACTERISTIQUES-CARACTERISTIQUES_MARNAGE-CARACTERISTIQUES_MARNAGE_CONSIGNE-CARACTERISTIQUES_MARNAGE_CONSIGNE-NIVT']) {
			element['CARACTERISTIQUES-CARACTERISTIQUES_MARNAGE-CARACTERISTIQUES_MARNAGE_CONSIGNE-CARACTERISTIQUES_MARNAGE_CONSIGNE-NIVT'] = element['CARACTERISTIQUES-CARACTERISTIQUES_MARNAGE-CARACTERISTIQUES_MARNAGE_CONSIGNE-CARACTERISTIQUES_MARNAGE_CONSIGNE-NIVT'] + "m"
		}
		if (element['CARACTERISTIQUES-CARACTERISTIQUES-PR_PROFONDEUR']) {
			element['CARACTERISTIQUES-CARACTERISTIQUES-PR_PROFONDEUR'] = element['CARACTERISTIQUES-CARACTERISTIQUES-PR_PROFONDEUR'] + "m"
		}
		 if (element['CARACTERISTIQUES-CARACTERISTIQUES_REFOULEMENT-CARACTERISTIQUES_REFOULEMENT-LONGUEUR']) {
			 element['CARACTERISTIQUES-CARACTERISTIQUES_REFOULEMENT-CARACTERISTIQUES_REFOULEMENT-LONGUEUR'] = element['CARACTERISTIQUES-CARACTERISTIQUES_REFOULEMENT-CARACTERISTIQUES_REFOULEMENT-LONGUEUR'] + "m"
			element['CARACTERISTIQUES-CARACTERISTIQUES_REFOULEMENT-CARACTERISTIQUES_REFOULEMENT-LONGUEUR_LABEL']="Longueur"
		}
		 if (element['SURVERSE-SURVERSE_PRESENCE-SURVERSE_PRESENCE-PROF']) {
			 element['SURVERSE-SURVERSE_PRESENCE-SURVERSE_PRESENCE-PROF'] = element['SURVERSE-SURVERSE_PRESENCE-SURVERSE_PRESENCE-PROF'] + "m"
		 }

		 //Bache
		 /*if (element['CARACTERISTIQUES-CARACTERISTIQUES_BACHE-CARACTERISTIQUES_BACHE-DIMENSION_DIAM']) {
			 element['CARACTERISTIQUES-CARACTERISTIQUES_BACHE-CARACTERISTIQUES_BACHE-DIMENSION_DIAM'] = element['CARACTERISTIQUES-CARACTERISTIQUES_BACHE-CARACTERISTIQUES_BACHE-DIMENSION_DIAM'] + "m"
		 }*/
		 if (element['CARACTERISTIQUES-CARACTERISTIQUES_BACHE-CARACTERISTIQUES_BACHE-DIMENSION_LONG']) {
			 element['CARACTERISTIQUES-CARACTERISTIQUES_BACHE-CARACTERISTIQUES_BACHE-DIMENSION_LONG'] = element['CARACTERISTIQUES-CARACTERISTIQUES_BACHE-CARACTERISTIQUES_BACHE-DIMENSION_LONG'] + "m"
		 }
		 
		 if (element['CARACTERISTIQUES-CARACTERISTIQUES_BACHE-CARACTERISTIQUES_BACHE-DIMENSION_DIAM']) {
			 element['SURFACE_BACHE'] = (parseInt(element['CARACTERISTIQUES-CARACTERISTIQUES_BACHE-CARACTERISTIQUES_BACHE-DIMENSION_DIAM']) * parseInt(element['CARACTERISTIQUES-CARACTERISTIQUES_BACHE-CARACTERISTIQUES_BACHE-DIMENSION_DIAM']) * Math.PI).toFixed(2) + " m²"
			 element['CARACTERISTIQUE_BACHE'] = "Ø" + element['CARACTERISTIQUES-CARACTERISTIQUES_BACHE-CARACTERISTIQUES_BACHE-DIMENSION_DIAM'] + "m"
		} else if (element['CARACTERISTIQUES-CARACTERISTIQUES_BACHE-CARACTERISTIQUES_BACHE-DIMENSION_LONG'] && element['CARACTERISTIQUES-CARACTERISTIQUES_BACHE-CARACTERISTIQUES_BACHE-DIMENSION_LARG']) {
			element['SURFACE_BACHE'] = (parseInt(element['CARACTERISTIQUES-CARACTERISTIQUES_BACHE-CARACTERISTIQUES_BACHE-DIMENSION_LONG']) * parseInt(element['CARACTERISTIQUES-CARACTERISTIQUES_BACHE-CARACTERISTIQUES_BACHE-DIMENSION_LARG'])) + " m²"
			element['CARACTERISTIQUE_BACHE'] = element['CARACTERISTIQUES-CARACTERISTIQUES_BACHE-CARACTERISTIQUES_BACHE-DIMENSION_LONG'] + "x" + element['CARACTERISTIQUES-CARACTERISTIQUES_BACHE-CARACTERISTIQUES_BACHE-DIMENSION_LARG']+"m"
		}
		
		 //Diamètre            
		 if (element['SURVERSE-SURVERSE_PRESENCE-SURVERSE_PRESENCE-DIAM']) {
			 element['SURVERSE-SURVERSE_PRESENCE-SURVERSE_PRESENCE-DIAM'] = "Ø" + element['SURVERSE-SURVERSE_PRESENCE-SURVERSE_PRESENCE-DIAM']
		 }
		 if (element['CARACTERISTIQUES-CARACTERISTIQUES_REFOULEMENT-CARACTERISTIQUES_REFOULEMENT-INT']) {
			 element['CARACTERISTIQUES-CARACTERISTIQUES_REFOULEMENT-CARACTERISTIQUES_REFOULEMENT-INT'] = "Ø" + element['CARACTERISTIQUES-CARACTERISTIQUES_REFOULEMENT-CARACTERISTIQUES_REFOULEMENT-INT']
		 }

		 //Ajout des m3/h
		 if (element['TARAGE-TARAGE-P1']) {
			 element['TARAGE-TARAGE-P1'] = element['TARAGE-TARAGE-P1'] + "m³/h"
		 }
		 if (element['TARAGE-TARAGE-P2']) {
			 element['TARAGE-TARAGE-P2'] = element['TARAGE-TARAGE-P2'] + "m³/h"
		 }
		 if (element['TARAGE-TARAGE-P1P2']) {
			 element['TARAGE-TARAGE-P1P2'] = element['TARAGE-TARAGE-P1P2'] + "m³/h"
		 }
		
		 if (element['TARAGE_OTHER_TARAGE']) {
			 element['TARAGE_OTHER_TARAGE'].forEach((obj, index) => {
				 //console.log(obj)
				 for (const [key, value] of Object.entries(obj)) {
					 if (key.includes("TARAGE-TARAGE_OTHER_TARAGE-TARAGE_OTHER_TARAGE-VALUE")) {
					 element['TARAGE_OTHER_TARAGE_' + parseInt((index + 1)) + '-' + key] = value + "m³/h";
					 // console.log('EQUIPEMENT_ANNEXE_' + parseInt((index + 1)) + '-' + key)
					 }
				 }
			 })
		 }
		
		if (element['CARACT_EQUIP_ANNEXE']) {
		  element['CARACT_EQUIP_ANNEXE'].forEach((obj, index) => {
			//console.log(obj)
			 for (const [key, value] of Object.entries(obj)) {
				  element['EQUIPEMENT_ANNEXE_' + parseInt((index + 1))+'-'+key]= value;
				   // console.log('EQUIPEMENT_ANNEXE_' + parseInt((index + 1)) + '-' + key)
				}
		  })
		}
		
		element['TARAGE_OTHER_TARAGE-1-label'] = "";
		element['TARAGE_OTHER_TARAGE-1-value'] = "";
		element['TARAGE_OTHER_TARAGE-2-label'] = "";
		element['TARAGE_OTHER_TARAGE-2-value'] = "";
		if (element['TARAGE_OTHER_TARAGE']) {
			if(element['TARAGE_OTHER_TARAGE'].length > 0){
				element['TARAGE_OTHER_TARAGE-1-label'] = element['TARAGE_OTHER_TARAGE'][0]["TARAGE-TARAGE_OTHER_TARAGE-TARAGE_OTHER_TARAGE-NAME"];
				element['TARAGE_OTHER_TARAGE-1-value'] = element['TARAGE_OTHER_TARAGE'][0]["TARAGE-TARAGE_OTHER_TARAGE-TARAGE_OTHER_TARAGE-VALUE"] + "m³/h";
			}
			if(element['TARAGE_OTHER_TARAGE'].length > 1){
				element['TARAGE_OTHER_TARAGE-2-label'] = element['TARAGE_OTHER_TARAGE'][1]["TARAGE-TARAGE_OTHER_TARAGE-TARAGE_OTHER_TARAGE-NAME"];
				element['TARAGE_OTHER_TARAGE-2-value'] = element['TARAGE_OTHER_TARAGE'][1]["TARAGE-TARAGE_OTHER_TARAGE-TARAGE_OTHER_TARAGE-VALUE"] + "m³/h";
			}
			if(element['TARAGE_OTHER_TARAGE'].length > 3){
				element['TARAGE_OTHER_TARAGE-3-label'] = element['TARAGE_OTHER_TARAGE'][3]["TARAGE-TARAGE_OTHER_TARAGE-TARAGE_OTHER_TARAGE-NAME"];
				element['TARAGE_OTHER_TARAGE-3-value'] = element['TARAGE_OTHER_TARAGE'][3]["TARAGE-TARAGE_OTHER_TARAGE-TARAGE_OTHER_TARAGE-VALUE"] + "m³/h";
			}
		}
		
		var cana_type_allaw = [{ key: "AMIANTE_C", value: "Amiante C." }, { key: "PVC", value: "PVC" }, { key: "BETON", value: "Béton" }, { key: "PEHD", value: "PEHD" }, { key: "PRV", value: "PRV" }, { key: "FONTE", value: "Fonte" }, { key: "GRES", value: "Grès" }, { key: "INCONNU", value: "Inconnu" }];
		if (element['CARACTERISTIQUES_CANALISATION']) {
			element['CANALISATION_OTHER']=[];
			element['CARACTERISTIQUES_CANALISATION'].forEach((obj, index) => {
				if(index<=2){
					for (const [key, value] of Object.entries(obj)) {
						if (key.includes("CARACTERISTIQUES-CARACTERISTIQUES_CANALISATION-CARACTERISTIQUES_CANALISATION-TYPE")) {
							if(cana_type_allaw.some(el => el.value === value)){
								var current_cana = cana_type_allaw.filter(el => el.value ==value)[0]
								element['CANA' + parseInt((index + 1)) + '-' + key + '-' + current_cana["key"]] = "X";
							}
						}else{
							element['CANA' + parseInt((index + 1)) + '-' + key] = value;
						}
						
					}
				}else{
				   // console.log(obj)
					textOther = "Canalisation " + parseInt((index + 1)) + ", type " + obj['CARACTERISTIQUES-CARACTERISTIQUES_CANALISATION-CARACTERISTIQUES_CANALISATION-TYPE'] + ", de diamètre " + obj['CARACTERISTIQUES-CARACTERISTIQUES_CANALISATION-CARACTERISTIQUES_CANALISATION-DIAM'] + " et de profondeur " + obj['CARACTERISTIQUES-CARACTERISTIQUES_CANALISATION-CARACTERISTIQUES_CANALISATION-PROF']+ "m;";
					 for (const [key, value] of Object.entries(obj)) {
						 //console.log(key)
						 //console.log(value)

						 /* if (key.includes("CARACTERISTIQUES-CARACTERISTIQUES_CANALISATION-CARACTERISTIQUES_CANALISATION-TYPE-")) {
							if (value == "1") {
								//element['CANA' + parseInt((index + 1)) + '-' + key] = "X";
								 textOther = textOther + key.replace("CARACTERISTIQUES-CARACTERISTIQUES_CANALISATION-CARACTERISTIQUES_CANALISATION-TYPE-","")
							}
						   
						 } */
					}
					element['CANALISATION_OTHER'].push(textOther)
				}
			 
			})
			element['CANALISATION_OTHER'] = element['CANALISATION_OTHER'].join(' ')
			//console.log(element)
			if (element['CANA1-CARACTERISTIQUES-CARACTERISTIQUES_CANALISATION-CARACTERISTIQUES_CANALISATION-PROF']) {
				element['CANA1-CARACTERISTIQUES-CARACTERISTIQUES_CANALISATION-CARACTERISTIQUES_CANALISATION-PROF'] = element['CANA1-CARACTERISTIQUES-CARACTERISTIQUES_CANALISATION-CARACTERISTIQUES_CANALISATION-PROF'] + "m"
			}

			if (element['CANA2-CARACTERISTIQUES-CARACTERISTIQUES_CANALISATION-CARACTERISTIQUES_CANALISATION-PROF']) {
				element['CANA2-CARACTERISTIQUES-CARACTERISTIQUES_CANALISATION-CARACTERISTIQUES_CANALISATION-PROF'] = element['CANA2-CARACTERISTIQUES-CARACTERISTIQUES_CANALISATION-CARACTERISTIQUES_CANALISATION-PROF'] + "m"
			}
			if (element['CANA3-CARACTERISTIQUES-CARACTERISTIQUES_CANALISATION-CARACTERISTIQUES_CANALISATION-PROF']) {
				element['CANA3-CARACTERISTIQUES-CARACTERISTIQUES_CANALISATION-CARACTERISTIQUES_CANALISATION-PROF'] = element['CANA3-CARACTERISTIQUES-CARACTERISTIQUES_CANALISATION-CARACTERISTIQUES_CANALISATION-PROF'] + "m"
			}
			 if (element['CANA1-CARACTERISTIQUES-CARACTERISTIQUES_CANALISATION-CARACTERISTIQUES_CANALISATION-DIAM']) {
				 element['CANA1-CARACTERISTIQUES-CARACTERISTIQUES_CANALISATION-CARACTERISTIQUES_CANALISATION-DIAM'] = "Ø" + element['CANA1-CARACTERISTIQUES-CARACTERISTIQUES_CANALISATION-CARACTERISTIQUES_CANALISATION-DIAM']
			 }
			 if (element['CANA2-CARACTERISTIQUES-CARACTERISTIQUES_CANALISATION-CARACTERISTIQUES_CANALISATION-DIAM']) {
				 element['CANA2-CARACTERISTIQUES-CARACTERISTIQUES_CANALISATION-CARACTERISTIQUES_CANALISATION-DIAM'] = "Ø" + element['CANA2-CARACTERISTIQUES-CARACTERISTIQUES_CANALISATION-CARACTERISTIQUES_CANALISATION-DIAM']
			 }
			 if (element['CANA3-CARACTERISTIQUES-CARACTERISTIQUES_CANALISATION-CARACTERISTIQUES_CANALISATION-DIAM']) {
				 element['CANA3-CARACTERISTIQUES-CARACTERISTIQUES_CANALISATION-CARACTERISTIQUES_CANALISATION-DIAM'] = "Ø" + element['CANA3-CARACTERISTIQUES-CARACTERISTIQUES_CANALISATION-CARACTERISTIQUES_CANALISATION-DIAM']
			 }
			
			//console.log(element)
		}
	})
}